import 'package:runwithme/providers/event.dart';
import 'package:runwithme/providers/events.dart';

List<Event> dummy = [
  Event(
    adminId: 1,
    averageDuration: 55,
    averageLength: 11,
    startingPintLong: 9.2,
    startingPintLat: 45.4,
    name: "PiewgfRun",
    maxParticipants: 420,
    currentParticipants: 69,
    id: 543524,
    difficultyLevel: 4,
    date: DateTime.now(),
    createdAt: DateTime.now(),
    averagePaceMin: 55,
    averagePaceSec: 76,
  ),
  Event(
    adminId: 1,
    averageDuration: 55,
    averageLength: 11,
    startingPintLong: 9.227,
    startingPintLat: 45.472,
    name: "PippoRun",
    maxParticipants: 45,
    currentParticipants: 45,
    id: 432,
    difficultyLevel: 4,
    date: DateTime.now(),
    createdAt: DateTime.now(),
    averagePaceMin: 55,
    averagePaceSec: 76,
  ),
  Event(
    adminId: 1,
    averageDuration: 55,
    averageLength: 11,
    startingPintLong: 9.221,
    startingPintLat: 45.492,
    name: "Pippodghfdgfdgqa gfdsag gagrg gfsdagrRun",
    maxParticipants: 420,
    currentParticipants: 69,
    id: 543476524,
    difficultyLevel: 3,
    date: DateTime.now(),
    createdAt: DateTime.now(),
    averagePaceMin: 55,
    averagePaceSec: 76,
  ),
  Event(
    adminId: 1,
    averageDuration: 55,
    averageLength: 11,
    startingPintLong: 9.242,
    startingPintLat: 45.446,
    name: "PippoRun",
    maxParticipants: 420,
    currentParticipants: 69,
    id: 5435543224,
    difficultyLevel: 2.5,
    date: DateTime.now(),
    createdAt: DateTime.now(),
    averagePaceMin: 55,
    averagePaceSec: 76,
  ),
  Event(
    adminId: 1,
    averageDuration: 55,
    averageLength: 11,
    startingPintLong: 9.271,
    startingPintLat: 45.417,
    name: "PippoRun",
    maxParticipants: 39,
    currentParticipants: 39,
    id: 543657524,
    difficultyLevel: 5,
    date: DateTime.now(),
    createdAt: DateTime.now(),
    averagePaceMin: 55,
    averagePaceSec: 76,
  ),
  Event(
    adminId: 1,
    averageDuration: 55,
    averageLength: 11,
    startingPintLong: 9.263,
    startingPintLat: 45.42,
    name: "PippoRun",
    maxParticipants: 420,
    currentParticipants: 69,
    id: 54353124,
    difficultyLevel: 1,
    date: DateTime.now(),
    createdAt: DateTime.now(),
    averagePaceMin: 55,
    averagePaceSec: 76,
  ),
  Event(
    adminId: 1,
    averageDuration: 55,
    averageLength: 11,
    startingPintLong: 9.265,
    startingPintLat: 45.41,
    name: "PippoRun",
    maxParticipants: 420,
    currentParticipants: 69,
    id: 5524,
    difficultyLevel: 1.5,
    date: DateTime.now(),
    createdAt: DateTime.now(),
    averagePaceMin: 55,
    averagePaceSec: 76,
  ),
  Event(
    adminId: 1,
    averageDuration: 55,
    averageLength: 11,
    startingPintLong: 9.211,
    startingPintLat: 45.44,
    name: "PippoRun",
    maxParticipants: 420,
    currentParticipants: 69,
    id: 5435,
    difficultyLevel: 4,
    date: DateTime.now(),
    createdAt: DateTime.now(),
    averagePaceMin: 55,
    averagePaceSec: 76,
  ),
  Event(
    adminId: 1,
    averageDuration: 55,
    averageLength: 11,
    startingPintLong: 9.29,
    startingPintLat: 45.49,
    name: "PippoRun",
    maxParticipants: 420,
    currentParticipants: 69,
    id: 5435324,
    difficultyLevel: 4,
    date: DateTime.now(),
    createdAt: DateTime.now(),
    averagePaceMin: 55,
    averagePaceSec: 76,
  ),
  Event(
    adminId: 1,
    averageDuration: 55,
    averageLength: 11,
    startingPintLong: 9.21,
    startingPintLat: 45.49,
    name: "PippoRun",
    maxParticipants: 420,
    currentParticipants: 69,
    id: 512324,
    difficultyLevel: 4,
    date: DateTime.now(),
    createdAt: DateTime.now(),
    averagePaceMin: 55,
    averagePaceSec: 76,
  ),
  Event(
    adminId: 1,
    averageDuration: 55,
    averageLength: 11,
    startingPintLong: 9.276,
    startingPintLat: 45.411,
    name: "PippoRun",
    maxParticipants: 420,
    currentParticipants: 69,
    id: 345,
    difficultyLevel: 1.5,
    date: DateTime.now(),
    createdAt: DateTime.now(),
    averagePaceMin: 55,
    averagePaceSec: 76,
  ),
  Event(
    adminId: 1,
    averageDuration: 55,
    averageLength: 11,
    startingPintLong: 9.287,
    startingPintLat: 45.42,
    name: "PippoRun",
    maxParticipants: 420,
    currentParticipants: 69,
    id: 2,
    difficultyLevel: 4,
    date: DateTime.now(),
    createdAt: DateTime.now(),
    averagePaceMin: 55,
    averagePaceSec: 76,
  ),
  Event(
    adminId: 1,
    averageDuration: 55,
    averageLength: 11,
    startingPintLong: 9.2133,
    startingPintLat: 45.41,
    name: "PippoRun",
    maxParticipants: 420,
    currentParticipants: 69,
    id: 78,
    difficultyLevel: 4,
    date: DateTime.now(),
    createdAt: DateTime.now(),
    averagePaceMin: 55,
    averagePaceSec: 76,
  ),
  Event(
    adminId: 1,
    averageDuration: 55,
    averageLength: 11,
    startingPintLong: 9.2,
    startingPintLat: 45.49,
    name: "PippoRun",
    maxParticipants: 420,
    currentParticipants: 69,
    id: 54321,
    difficultyLevel: 4,
    date: DateTime.now(),
    createdAt: DateTime.now(),
    averagePaceMin: 55,
    averagePaceSec: 76,
  ),
  Event(
    adminId: 1,
    averageDuration: 55,
    averageLength: 11,
    startingPintLong: 9.19,
    startingPintLat: 45.45,
    name: "PippoRun",
    maxParticipants: 420,
    currentParticipants: 69,
    id: 4672,
    difficultyLevel: 1.5,
    date: DateTime.now(),
    createdAt: DateTime.now(),
    averagePaceMin: 55,
    averagePaceSec: 76,
  ),
  Event(
    adminId: 1,
    averageDuration: 55,
    averageLength: 11,
    startingPintLong: 9.26,
    startingPintLat: 45.38,
    name: "PippoRun",
    maxParticipants: 420,
    currentParticipants: 69,
    id: 567893,
    difficultyLevel: 4,
    date: DateTime.now(),
    createdAt: DateTime.now(),
    averagePaceMin: 55,
    averagePaceSec: 76,
  ),
  Event(
    adminId: 1,
    averageDuration: 55,
    averageLength: 11,
    startingPintLong: 9.21,
    startingPintLat: 45.46,
    name: "PippoRun",
    maxParticipants: 420,
    currentParticipants: 69,
    id: 67843,
    difficultyLevel: 4,
    date: DateTime.now(),
    createdAt: DateTime.now(),
    averagePaceMin: 55,
    averagePaceSec: 76,
  ),
  Event(
    adminId: 1,
    averageDuration: 55,
    averageLength: 11,
    startingPintLong: 9.22,
    startingPintLat: 45.43,
    name: "PippoRun",
    maxParticipants: 420,
    currentParticipants: 69,
    id: 35563,
    difficultyLevel: 4,
    date: DateTime.now(),
    createdAt: DateTime.now(),
    averagePaceMin: 55,
    averagePaceSec: 76,
  ),
];
